### ISSUE TITLE
Update README with temporary instructions on getting the right `terrastories/terrastories` image built for this

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/offline-field-kit#1]
Currently, when you run `bash install.sh` as per the readme, and load `terrastories.local`, the map doesn't load:
```
api.mapbox.com/styles/v1/mapbox/streets-v11?access_token=pk.ey:1 
Failed to load resource: the server responded with a status of 401 (Unauthorized)
mapbox-gl.js:31 
Error: Unauthorized: you may have provided an invalid Mapbox access token. See https://docs.mapbox.com/api/overview/#access-tokens-and-token-scopes at mapbox-gl.js:31:9233
```

This is because this repository builds `terrastories/terrastories:latest` from Dockerhub which is not yet updated with the latest maplibre/pmtiles changes. Since this `offline-field-kit` repo is now public, it's probably best that we leave a quick note indicating that the setup workflow in the readme is still WIP, and for this repo to actually work, one has to build terrastories with the right branch locally and use that image instead of what's on Dockerhub.

(After 2 months of being gone from Terrastories work, I totally forgot about this myself...)

**Comment by lauramosher** [comment]
@rudokemper This is obsolete now, yeah?

**Comment by rudokemper** [comment]
Yes!
